export {default as Navbar} from './Navbar'
export {default as Home} from './Home'
export {default as Map} from './Map'
export {default as Search} from './Search'
export {default as Info} from './Info'
export {default as WordCloud} from './WordCloud'
export {default as Contributors} from './Contributors'
export {default as ChartPie} from './ChartPie'
